---
#
# EECS 4287/5287: Principles of Cloud Computing
# Author: Team 4 and 5 Final Project
#
# Final Project Playbook
# # ####################################################
# # ## Play 1: Get facts from all our VMs

# # # Here I show the use of import_tasks from child playbooks
# ####################################################
# - name: "Play 1: Install packages on local VMs"
#   hosts:
#     MyLocalVMs          # specified in the MyInventory file
#   remote_user:
#     ubuntu      # note that the user is ubuntu for
#                              # vagrant-created VM else use the
#                              # appropriate user name

#   # gather_facts: yes          # We ask Ansible to collect all facts
#   # become: yes
#   # become_user: ubuntu            # No need for sudo as we are not installing anything

#   tasks:    # the task to be performed (here I am showing the effect of include_)
#   - include_tasks: tasks/playbook_local_vm_packages.yml

# ####################################################
# ## Play 2: Create Chameleon VMs
# ####################################################
# - name: "Play 2: Create Chameleon instances"
#   hosts:
#     MyLocalVMs
#   connection: local
#   collections:
#     - openstack.cloud

#   tasks:    # the task to be performed (here I am showing the effect of include_)
#   - include_tasks: tasks/playbook_chameleon_creation.yml

- name: "Add host to VMs"
  hosts:
    MyLocalVMs
  connection: local
  tasks:
  - name: "Add VM2 to MyChameleonVMs dynamically"
    add_host:
      hostname: 129.114.26.3
      ansible_connection: ssh
      ansible_ssh_private_key_file: "/home/vagrant/.ssh/jh_ku_chameleon.key"
      groups: MyChameleonVMs

  - name: "Add VM3 to MyChameleonVMs dynamically"
    add_host:
      hostname: 129.114.27.157
      ansible_connection: ssh
      ansible_ssh_private_key_file: "/home/vagrant/.ssh/jh_ku_chameleon.key"
      groups: MyChameleonVMs

# ####################################################
# ## Play 3: Install Packages on Chameleon VMs
# ####################################################
# - name: "Play 3: Installing packages on the VMs"
#   hosts: MyChameleonVMs  # remember, the requestor is the local machine
#     #update ubuntu machine
#   remote_user:
#      cc
#   tasks:
#   - include_tasks: tasks/playbook_install_packages_cloud.yml

# ####################################################
# ## Play 4: Configure cloud files
# ####################################################
# - name: "Play 4: Configuring cloud firewall settings"
#   hosts: MyChameleonVMs  # remember, the requestor is the local machine
#     #update ubuntu machine
#   remote_user:  cc
#   become: yes
#   tasks:
#   - include_tasks: tasks/playbook_cloud_configuration.yml

# ####################################################
# ## Play 5: Installing docker and kubernetes
# ####################################################
# - name: "Play 5: Install Packages, Docker, and Kubernetes"
#   hosts: MyChameleonVMs  # remember, the requestor is the local machine
#   remote_user:  cc
#   become: yes
#   tasks:
#   - include_tasks: tasks/playbook_chameleon_docker_kb_install.yml

# ####################################################
# ## Play 6: Start Kubernetes and taint master on VM2
# ####################################################
# - name: "Play 6: Start Kubernetes and taint master on VM2"
#   hosts: MyChameleonVMs[0]
#   remote_user:  cc
#   become: yes
#   tasks:
#   - include_tasks: tasks/playbook_chameleon_VM2_KB_start.yml

# ####################################################
# ## Play 7: Start Kubernetes on VM3
# ####################################################
# - name: "Play 7: Start Kubernetes and taint master on VM2"
#   hosts: MyChameleonVMs[1]
#   remote_user:  cc
#   become: yes
#   tasks:
#   - include_tasks: tasks/playbook_chameleon_VM3_KB_start.yml

# ####################################################
# ## Play 8: Start docker image and create registry
# ####################################################
# - name: "Play 8: Run docker pipeline for zookeeper, kafka"
#   hosts: MyChameleonVMs[0]
#   remote_user:  cc
#   become: yes
#   tasks:
#   - include_tasks: tasks/playbook_docker_img_reg.yml
#   - include_tasks: tasks/playbook_zookeeper_service_start.yml
#   - include_tasks: tasks/playbook_kafka_service_start.yml
#   - include_tasks: tasks/playbook_couchdb_img.yml
#   - include_tasks: tasks/playbook_couchdb_run.yml


# ####################################################
# ## Play 10: Run Spark Pipeline
# ####################################################
# - name: "Play 10: Run Spark Pipeline"
#   hosts: MyChameleonVMs[0]
#   remote_user:  cc
#   become: yes
#   tasks:
#   - include_tasks: tasks/playbook_spark_img.yml
#   - include_tasks: tasks/playbook_spark_master.yml
#   - include_tasks: tasks/playbook_spark_driver_worker.yml

################## RUN THIS AFTER MODEL TRAINING ####################

# ####################################################
# ## Play 12: Run Consumer
# ####################################################
# - name: "Play 12: Run Consumer"
#   hosts: MyChameleonVMs[0]
#   remote_user:  cc
#   become: yes
#   tasks:
#   - include_tasks: tasks/playbook_consumer_img_run.yml


####################################################
## Play 11: Run Nginx Pipeline
####################################################
- name: "Play 11: Run Nginx Pipeline and Flask"
  hosts: MyChameleonVMs[0]
  remote_user:  cc
  become: yes
  tasks:
  - include_tasks: tasks/playbook_nginx_deployment.yml
  - include_tasks: tasks/playbook_flask_deployment.yml
...
