# Author:Team 4 and 5
# Description: Dockerfile for flask deployment
#
# First, use the latest ubuntu image, which points to the
# latest LTS image, currently 20.04LTS
FROM ubuntu:latest

# Now install the needed python packages
RUN apt-get -y update && apt-get install -y net-tools python3 gcc
RUN apt-get install -y python3-dev python3-pip
RUN python3 -m pip install --upgrade pip

COPY requirements.txt /requirements.txt
RUN pip3 install -r requirements.txt
RUN pip3 install tensorflow
RUN pip3 install pandas
RUN pip3 install couchdb
RUN pip3 install kafka-python
RUN pip3 install numpy

COPY app.py /

RUN mkdir -p /api
COPY HelloApiHandler.py /api/