# Author: Aadarsh Jha and Ashwin Kumar
# Description: Dockerfile for kafka and zookeeper
#
# First, use the latest ubuntu image, which points to the
# latest LTS image, currently 20.04LTS
FROM ubuntu:latest
#
# Now install the needed python packages
RUN apt-get -y update && apt-get install -y net-tools python3 gcc
RUN apt-get install -y python3-dev python3-pip
RUN python3 -m pip install --upgrade pip
RUN pip3 install --upgrade kafka-python
RUN pip3 install --upgrade CouchDB
RUN pip3 install --upgrade tensorflow

COPY consumer.py /
COPY mnist_model.h5 /